version: "3.8"
services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: object_store_app_dev
      POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: l8trKyh6WCtWUs7NuTtzKSW6iUERHMtxP230Ljdezz4H2Jo4KPH9cz
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
  object_store:
    image: minio/minio
    command: server --console-address ":9001" /home/shared
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      # - MINIO_ACCESS_KEY=nRxhyuGuk3DJPSl7JRTPKd5i75lgCGhpLgFpDW97mK2wMqXc2DntN+ArbLekTCpX
      - MINIO_ACCESS_KEY=access_key
      # - MINIO_SECRET_KEY=WFk0kE7wTcPa0stgx6aHnNABaSpEkl4amhD9tUesnJKkoiPdBPCNBqdAaDol0BAV
      - MINIO_SECRET_KEY=secret_key

  minio:
    image: minio/mc
    environment:
      - MINIO_HOST=object_store:9000
      - MINIO_ACCESS_KEY=access_key
      - MINIO_SECRET_KEY=secret_key
